apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    name: node-proxy-service
spec:
  type: NodePort
  ports:
  - port: 8808
    targetPort: 8808
    nodePort: 8808
    name: proxy-port
    protocol: TCP
  selector:
    app: np-ps-1
    
